# Generated by Django 4.1.7 on 2023-03-30 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='город')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='страна')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='район')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localityName', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='н.п.')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Малый нп',
                'verbose_name_plural': 'Малые нп',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastnameCyrillic', models.CharField(max_length=40, verbose_name='фамилия')),
                ('firstnameCyrillic', models.CharField(max_length=40, verbose_name='имя')),
                ('patronymicCyrillic', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='отчество')),
                ('lastnameLatin', models.CharField(max_length=40, verbose_name='фамилия (латин.)')),
                ('firstnameLatin', models.CharField(max_length=40, verbose_name='имя (англ.)')),
                ('patronymicLatin', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='отчество (англ.)')),
                ('birthDate', models.DateField(verbose_name='дата рождения')),
                ('gender', models.CharField(choices=[('M', 'М'), ('F', 'Ж')], max_length=2, verbose_name='пол')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('cityOfBirth', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.cities', verbose_name='город рождения')),
                ('countryOfBirth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.countries', verbose_name='страна рождения')),
                ('districtOfBirth', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.districts', verbose_name='район рождения')),
                ('localityOfBirth', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.localities', verbose_name='н.п. рождения')),
            ],
            options={
                'verbose_name': 'Физлицо',
                'verbose_name_plural': 'Физлица',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='область')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='улица')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='SubsFed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfName', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='СФ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
            ],
            options={
                'verbose_name': 'Субъект РФ',
                'verbose_name_plural': 'Субъекты РФ',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата регистрации')),
                ('house', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='дом')),
                ('body', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='корпус')),
                ('flat', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='квартира')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.cities', verbose_name='город')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.districts', verbose_name='район')),
                ('locality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.localities', verbose_name='н.п.')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='лицо')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.regions', verbose_name='область')),
                ('sf', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.subsfed', verbose_name='субъект РФ')),
                ('street', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.streets', verbose_name='улица')),
            ],
            options={
                'verbose_name': 'Место регистрации',
                'verbose_name_plural': 'Места регистрации',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='regOfBirth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.regions', verbose_name='область'),
        ),
        migrations.AddField(
            model_name='person',
            name='sfOfBirth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.subsfed', verbose_name='субъект РФ'),
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='IDphotos', verbose_name='фото')),
                ('passport_num', models.CharField(max_length=30, unique=True, verbose_name='номер ID')),
                ('idType', models.CharField(choices=[('P', 'Паспорт'), ('R', 'Вид на жительство')], default='P', max_length=1, verbose_name='тип ID')),
                ('dateOfIssue', models.DateField(default=datetime.date.today, verbose_name='дата выдачи')),
                ('authority', models.CharField(choices=[('MIA', 'МВД'), ('MFA', 'МИД')], max_length=3, verbose_name='кем выдан')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='владелец ID')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
